#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define SCREEN_WIDTH 900
#define SCREEN_HEIGHT 900
#define TILE_SIZE 100
#define SIZE_X SCREEN_WIDTH / TILE_SIZE
#define SIZE_Y SCREEN_HEIGHT / TILE_SIZE

#define START_RED 50
#define START_GREEN 100
#define START_BLUE 20

#define END_RED 120
#define END_GREEN 200
#define END_BLUE 100

#endif //DEFINITIONS_H
